name: Deploy on push to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Updated secret name for SSH private key
        run: |
          echo "${{ env.SSH_PRIVATE_KEY }}" > deploy_key.pem  # Updated file name for the private key
          chmod 600 deploy_key.pem  # Updated file name for the private key

      - name: Connect to Server (all following steps use this connection)
        uses: webfactory/ssh-agent@v0.5.3  # Updated action for SSH agent setup
        with:
          ssh-private-key: deploy_key.pem  # Updated file name for the private key

      - name: Git Checkout and Pull (uses established connection)
        run: |
          cd /home/ubuntu/frontend && \
            git checkout staging && git stash && git pull origin staging

      - name: Install and Build (uses established connection)
        run: |
          cd /home/ubuntu/frontend && \
            sudo apt update && sudo apt install -y npm && \
            npm install && npm run build

      - name: Collect Static and Restart Gunicorn (uses established connection)
        run: |
          cd /home/ubuntu/django-app/climatenet && \
            source venv/bin/activate && \
            python3 manage.py collectstatic --noinput && \
            sudo systemctl restart gunicorn.service
