on:
  push:
    branches:
      - deploy_test

name: Deploy on push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up SSH
      - name: Set up SSH
        run: |
          # Write the SSH private key to a file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
          # Set appropriate permissions for the SSH key
          chmod 600 ssh_key.pem
          # Create a config file with SSH connection details
          printf "Host myserver\n" \
                 "  HostName ${{ secrets.EC2_IP }}\n" \
                 "  User ${{ secrets.EC2_USERNAME }}\n" \
                 "  IdentityFile /github/workspace/ssh_key.pem\n" \
                 "  StrictHostKeyChecking no\n" > ~/.ssh/config

      # Step 2: Git Checkout and Pull
      - name: Git Checkout and Pull
        run: |
          # SSH into the server and navigate to the project directory
          ssh myserver 'cd /home/ubuntu/frontend &&' \
                       'git checkout deploy_test &&' \
                       'git pull origin deploy_test'

      # Step 3: Install and Build
      - name: Install and Build
        run: |
          # SSH into the server and install dependencies and build the project
          ssh myserver 'cd /home/ubuntu/frontend &&' \
                       'npm install && npm run build'

      # Step 4: Collect Static and Restart Gunicorn
      - name: Collect Static and Restart Gunicorn
        run: |
          # SSH into the server, navigate to Django project directory, collect static files, and restart Gunicorn
          ssh myserver 'cd && cd django-app/climatenet &&' \
                       'echo yes | python3 manage.py collectstatic &&' \
                       'sudo systemctl restart gunicorn.service'
